### ISSUE TITLE
It's a good job, but it doesn't mention aim-fas. Aim-fas is similar to this article.

### ISSUE THREAD

**Issue by tfygg** [rshaojimmy/AAAI2020-RFMetaFAS#10]
It's a good job, but it doesn't mention aim-fas. Aim-fas is similar to this article.

https://github.com/qyxqyx/AIM_FAS

**Comment by rshaojimmy** [comment]
Hi,

1. It seems that your mentioned aim-fas is also an AAAI 2020 paper and we do not know this paper until it is published at the same time as ours.

2. Our paper focuses on Domain Generalization and it seems that your mentioned aim-fas exploits the few-shot in their paper. This means that we do not have any clue in the target domain while aim-fas can fine-tune with target domain data in the training.

3. Our paper aims to use domain knowledge to learn a regularized meta-learning method for FAS instead of directly using the few-shot meta-learning method such as MAML.

As you said, we are also confused that your mentioned aim-fas is also a good job, but why it doesn't mention our paper. Aim-fas is similar to ours. haha.

Thanks.
