### ISSUE TITLE
some questions about datasets partitioning

### ISSUE THREAD

**Issue by roger-cv** [rshaojimmy/AAAI2020-RFMetaFAS#15]
nice, it is a good job.but,when i run it ,some quetions occers.as shown below:
![3](https://user-images.githubusercontent.com/31872115/88538704-65a5b900-d042-11ea-8c90-36f88e87817d.png)
i do not know the composition of documents,please show me the  hierarchy of data set files. looking forward to your replay.

**Comment by rshaojimmy** [comment]
Hi,

Thanks for your interest in our work.

You need to download the datasets and extract the frames. Then building the real and fake list files (image_list_real and image_list_fake) according to the extracted frames of real and fake faces. 

I am sorry that I cannot provide your datasets because of the copyright issue. Please ask the datasets providers for the data.

Thanks.
