### ISSUE TITLE
Data Processing Problem

### ISSUE THREAD

**Issue by woxue** [rshaojimmy/AAAI2020-RFMetaFAS#9]
I have some problem about how to process the origin dataset.
1. How do you change the video data into image? How often should I get a screenshot? (Such as every 5 frames?) Could you tell me the whole num of images in every dataset after the pre-processing?
2. Should the input image been croped to face part or remain the whole scene?(In my experiment, PRNet can only generate depth for face image.)

Thanks for your great work and hope for relpy!

**Comment by rshaojimmy** [comment]
Hi,

1. To balance the number of extracted frames from different datasets, we extract frames in every 2 to 5 frames for different datasets. This produces around 40000 to 60000 frames for different datasets after pre-processing.

2. We just use the normal face alignment package to crop the face part which contains some parts of the background. You can refer to the attention map visualization in our paper for more details. PRnet only generates depth for face image because it does the depth prediction based on the detected face landmarks.

Thanks.

**Comment by woxue** [comment]
Thanks for your reply.
